trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @angular/cli
      npm install
      ng build
    displayName: 'npm install and build'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/dist' # Update this path based on your Angular build output
      ArtifactName: 'angular-app'
      publishLocation: 'Container'
    displayName: 'Publish build artifact'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/dist' # Update this path based on your Angular build output
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/angular-app.zip'
      replaceExistingArchive: true
    displayName: 'Compress artifact as .zip'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'compressed-artifact'
      publishLocation: 'Container'
    displayName: 'Publish compressed artifact'
